name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

version: 2.2.0

publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0 #removed because code generator throws exception on iOs
